name: Generate Snake

on:
  schedule:
    # Runs at 12am UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch: # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: My-Mation
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to snake-preview branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake-preview   # <── changed here
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

